### ISSUE TITLE
После обновления платформы скрипт перестал отрабатывать

### ISSUE THREAD

**Issue by djtcp** [kulpin74/zabbix-1c#20]
C:\WINDOWS\system32>C:\zabbix\scripts\ib_list.py
Traceback (most recent call last):
  File "C:\zabbix\scripts\ib_list.py", line 25, in <module>
    cluster_res = subprocess.check_output(['rac', 'cluster', 'list']).decode(C_PAGE).strip()
  File "C:\Program Files\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by djtcp** [comment]
через время заработало

**Comment by kulpin74** [comment]
Я бы предположил что переменную PATH изменили уже после инсталляции, когда и заработало. Опять же предположу что после инсталляции или непосредственно перед ней удалили старую платформу и скрипты перестали находить RAC.
